#!/usr/bin/env python

import os
import atexit
import readline

history = os.getenv(
  'PYTHON_HISTFILE',
  os.path.join(os.path.expanduser('~'), '.python_history')
)

try:
  readline.read_history_file(history)
except IOError:
  pass

atexit.register(readline.write_history_file, history)
