#!/usr/bin/env sh

REPO=$HOME/work/personal/dotfiles

FILES="bashrc gitconfig vim tmux.conf alacritty.yml"

for dotfile in $FILES; do
  test "$1" = "-f" && rm -rf "$HOME/.$dotfile"
  ln -Ts "$REPO/$dotfile" "$HOME/.$dotfile"
done

if [ ! -d "$HOME/work/contrib/asdf" ]; then
  git clone https://github.com/asdf-vm/asdf "$HOME/work/contrib/asdf"
fi

if [ ! -d "$HOME/work/contrib/password-store" ]; then
  git clone https://git.zx2c4.com/password-store "$HOME/work/contrib/password-store"
fi
