#!/usr/bin/env sh

REPO=$HOME/work/personal/dotfiles

FILES="bashrc gitconfig vim"

for dotfile in $FILES; do
  test "$1" = "-f" && rm -rf "$HOME/.$dotfile"
  ln -s "$REPO/$dotfile" "$HOME/.$dotfile"
done
