#!/usr/bin/env bash

activate() {
  py=".env/bin/activate"
  [ -f "$py" ] && . "$py"

  py=".venv/bin/activate"
  [ -f "$py" ] && . "$py"

  js="node_modules"
  if [ -d "$js" ]; then
    export _PREV_PATH_WITHOUT_NPM="$PATH"
    export _PREV_PS1_WITHOUT_NPM="$PS1"

    export PATH="$(npm bin):$PATH"
    export PS1="[npm:$(basename "$PWD")]$PS1"

    deactivate() {
      export PATH="$_PREV_PATH_WITHOUT_NPM"
      export PS1="$_PREV_PS1_WITHOUT_NPM"
      unset -f deactivate
    }
  fi
}

alias pubkey='ssh-keygen -yf'
function ecm { git add $1 && gcm "${1%*.*} solved"; }
function lip { /sbin/ifconfig | awk '/inet6?/{print $2}' | sort -u; }
