#!/usr/bin/env bash

alias gl='git gl'
alias gs='git status'
alias gap='git add -p'
alias gcm='git commit -m'
alias gd='git diff'
alias gdc='git diff --cached'
alias gai='git add -i'
function gr { git rebase -i HEAD~$1; }
