#!/usr/bin/env bash

shopt -s histappend
export HISTCONTROL=ignoredups
export HISTSIZE=
export HISTFILESIZE=
export PROMPT_COMMAND=

export HISTFILE="$HOME/history/bash"
export MYSQL_HISTFILE="$HOME/history/mysql"
export PSQL_HISTORY="$HOME/history/psql"
export NODE_REPL_HISTORY="$HOME/history/node"
export LESSHISTFILE="$HOME/history/less"
