#!/usr/bin/env bash

if command -v pass > /dev/null; then
  export PASSWORD_STORE_DIR="$HOME/secrets/passwords/"

  if [ -f "$HOME/work/personal/wifi/completion" ]; then
    source "$HOME/work/personal/wifi/completion"
  fi

  source "$HOME/work/contrib/password-store/src/completion/pass.bash-completion"

  export LIFEONMARS_PASSWORD_STORE_DIR="lifeonmarspt/"
fi
