#!/usr/bin/env bash

if command -v pass > /dev/null; then
  export PASSWORD_STORE_DIR="$HOME/passwords/store/"

  if [ -f "$HOME/work/personal/wifi/completion" ]; then
    source "$HOME/work/personal/wifi/completion"
  fi
fi
