#! /usr/bin/env bash

tico_pwd() {
  local dir="$PWD"

  if [[ "$HOME" == ${dir:0:${#HOME}} ]] ; then
    dir="~${dir:${#HOME}}"
  fi

  echo "$dir" | tico
}

if command -v tico > /dev/null; then
  export PS1='\u@\h:$(tico_pwd)\$ '
else
  export PS1='\u@\h:\w\$ '
fi
