#!/usr/bin/env bash

if command -v tico > /dev/null; then
  tico_pwd() {
    local dir="$PWD"

    if [ "$HOME" = ${dir:0:${#HOME}} ]; then
      dir="~${dir:${#HOME}}"
    fi

    tico "$dir"
  }

  export PS1='\u@\h:$(tico_pwd)\$ '
else
  export PS1='\u@\h:\w\$ '
fi
